/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package FrontEnd;

import java.awt.*;
import java.time.LocalDateTime;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author John
 */
public class CreateContentWindow extends javax.swing.JDialog {

    private String contentText = "";
    private String contentImgDir = "";
    private String type;
    private LocalDateTime time;
    private MyCanvas ImagePreview;
    private static final String postsPath = "content.json";

    /**
     * Creates new form NewJDialog
     *
     * @param parent
     * @param modal
     */
    public CreateContentWindow(java.awt.Frame parent, boolean modal, String type) {
        super(parent, modal);
        setTitle("Create Content");
        setPreferredSize(new Dimension(400, 375));
        setResizable(false);
        setLocationRelativeTo(null);

        this.type = type;

        ImagePreview = new MyCanvas("");
        add(ImagePreview);
        ImagePreview.setBounds(10, 119, 368, 153);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        postTextEditorTxtArea = new javax.swing.JTextArea();
        postBtn = new javax.swing.JButton();
        addImageBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        removeImgBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        postTextEditorTxtArea.setColumns(20);
        postTextEditorTxtArea.setRows(5);
        postTextEditorTxtArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(postTextEditorTxtArea);

        postBtn.setText("Share");
        postBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postBtnActionPerformed(evt);
            }
        });

        addImageBtn.setText("Add Image");
        addImageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        removeImgBtn.setText("Remove Image");
        removeImgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeImgBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addImageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeImgBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(postBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addImageBtn)
                    .addComponent(cancelBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeImgBtn)
                    .addComponent(postBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postBtnActionPerformed
        if ("s".equals(type) && !"".equals(contentImgDir) && !"".equals(postTextEditorTxtArea.getText())) {
            JOptionPane.showMessageDialog(this, "Story must be text or image (can't be both)", "Input error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (!"".equals(postTextEditorTxtArea.getText())) {
                contentText = "<html><div style='width:90px;'>" + postTextEditorTxtArea.getText() + "</div></html>";
            }
            time = LocalDateTime.now();
            dispose();
        }
    }//GEN-LAST:event_postBtnActionPerformed

    private void addImageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser("D:");
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setDialogTitle("Select a .txt file");
        FileNameExtensionFilter restrict = new FileNameExtensionFilter("image", "jpg", "png", "jpeg");
        fileChooser.addChoosableFileFilter(restrict);

        int response = fileChooser.showOpenDialog(null);
        if (response == JFileChooser.APPROVE_OPTION) {
            contentImgDir = fileChooser.getSelectedFile().getAbsolutePath();
            ImagePreview.changePicture(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_addImageBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        contentText = "";
        contentImgDir = "";
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void removeImgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeImgBtnActionPerformed
        contentImgDir = "";
        ImagePreview.changePicture("");
    }//GEN-LAST:event_removeImgBtnActionPerformed

    protected String getContentText() {
        return contentText;
    }

    protected String getContentImgDir() {
        return contentImgDir;
    }

    public LocalDateTime getTime() {
        return time;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateContentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateContentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateContentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateContentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateContentWindow dialog = new CreateContentWindow(new javax.swing.JFrame(), true, "p");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addImageBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton postBtn;
    private javax.swing.JTextArea postTextEditorTxtArea;
    private javax.swing.JButton removeImgBtn;
    // End of variables declaration//GEN-END:variables
}
