/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import connecthub.*;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author ADMIN
 */
public class Profile extends javax.swing.JFrame {
     User user;
    /**
     * Creates new form Profile
     */

    public Profile(User user) {
        initComponents();
        this.user=user;

        
        loadCoverPhoto();
        loadProfilePhoto();
        loadUserDetails();
       // loadUserPosts();
        loadUserFriends();  
  
    }
    private void loadCoverPhoto() {
     try {
        Image coverPhoto = new ImageIcon(user.getCoverPhoto()).getImage();
        Image scaledCoverPhoto = coverPhoto.getScaledInstance(CoverPhotoPanel.getWidth(), CoverPhotoPanel.getHeight(), Image.SCALE_SMOOTH);

 
        JPanel coverPhotoPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(scaledCoverPhoto, 0, 0, getWidth(), getHeight(), this);
            }
        };
        coverPhotoPanel.setBounds(0, 0, CoverPhotoPanel.getWidth(), CoverPhotoPanel.getHeight());
        CoverPhotoPanel.add(coverPhotoPanel);
        CoverPhotoPanel.repaint();
        loadProfilePhoto();
        // Ensure the panel updates
    } catch (Exception e) {
        JLabel errorLabel = new JLabel("Cover Photo Not Available");
        errorLabel.setHorizontalAlignment(SwingConstants.CENTER);
        CoverPhotoPanel.add(errorLabel);
        CoverPhotoPanel.repaint();
    }
    }

    private void loadProfilePhoto() {
 try {
        Image profilePhoto = new ImageIcon(user.getProfilePhoto()).getImage();
        Image scaledProfilePhoto = profilePhoto.getScaledInstance(ProfilePhotoPanel.getWidth(), ProfilePhotoPanel.getHeight(), Image.SCALE_SMOOTH);

        JPanel profilePhotoPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(scaledProfilePhoto, 0, 0, getWidth(), getHeight(), this);
            }
        };
        profilePhotoPanel.setBounds(0, 0, ProfilePhotoPanel.getWidth(), ProfilePhotoPanel.getHeight());
        ProfilePhotoPanel.add(profilePhotoPanel);
        ProfilePhotoPanel.repaint(); 
        loadUserDetails();
    } catch (Exception e) {
        JLabel errorLabel = new JLabel("Profile Photo Not Available");
        errorLabel.setHorizontalAlignment(SwingConstants.CENTER);
        ProfilePhotoPanel.add(errorLabel);
        ProfilePhotoPanel.repaint();
    }
    }

    private void loadUserDetails() {
        jLabel1.setText(user.getUsername());
        jLabel2.setText(user.getBio());
    }

//    private void loadUserPosts() {
//        JPanel postsPanel = new JPanel();
//        postsPanel.setLayout(new BoxLayout(postsPanel, BoxLayout.Y_AXIS));
//
//        for (String post : user.) {
//            JLabel postLabel = new JLabel(post);
//            postLabel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
//            postsPanel.add(postLabel);
//        }
//
//        PostsPanelScroll.setViewportView(postsPanel);
//    }
    private void loadUserFriends() {
        JPanel friendsPanel = new JPanel();
        friendsPanel.setLayout(new BoxLayout(friendsPanel, BoxLayout.Y_AXIS));

        for (User friend : user.getFriends()) {
            JLabel friendLabel = new JLabel(friend.getUsername() + " (" + (friend.isStatus()? "Online" : "Offline") + ")");
            friendLabel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
            friendsPanel.add(friendLabel);
        }

        FriendsPanelScroll.setViewportView(FriendsPanel);
    }
    public void reloadProfileDetails() {
        loadCoverPhoto();  
        loadProfilePhoto(); 
        loadUserDetails();   
        loadUserFriends();   
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        CoverPhotoPanel = new javax.swing.JPanel();
        ProfilePhotoPanel = new javax.swing.JPanel();
        SettingsWindow = new javax.swing.JButton();
        ReturnButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PostsPanelScroll = new javax.swing.JScrollPane();
        PostsPanel = new javax.swing.JPanel();
        FriendsPanelScroll = new javax.swing.JScrollPane();
        FriendsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profile Page");

        jLayeredPane1.setBackground(new java.awt.Color(153, 0, 255));

        CoverPhotoPanel.setBackground(new java.awt.Color(255, 102, 102));

        ProfilePhotoPanel.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout ProfilePhotoPanelLayout = new javax.swing.GroupLayout(ProfilePhotoPanel);
        ProfilePhotoPanel.setLayout(ProfilePhotoPanelLayout);
        ProfilePhotoPanelLayout.setHorizontalGroup(
            ProfilePhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        ProfilePhotoPanelLayout.setVerticalGroup(
            ProfilePhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        SettingsWindow.setText("Settings");
        SettingsWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsWindowActionPerformed(evt);
            }
        });

        ReturnButton.setText("Return");
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout CoverPhotoPanelLayout = new javax.swing.GroupLayout(CoverPhotoPanel);
        CoverPhotoPanel.setLayout(CoverPhotoPanelLayout);
        CoverPhotoPanelLayout.setHorizontalGroup(
            CoverPhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoverPhotoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CoverPhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CoverPhotoPanelLayout.createSequentialGroup()
                        .addComponent(ProfilePhotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CoverPhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CoverPhotoPanelLayout.createSequentialGroup()
                        .addComponent(ReturnButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SettingsWindow)))
                .addContainerGap())
        );
        CoverPhotoPanelLayout.setVerticalGroup(
            CoverPhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CoverPhotoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CoverPhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SettingsWindow)
                    .addComponent(ReturnButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(CoverPhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CoverPhotoPanelLayout.createSequentialGroup()
                        .addComponent(ProfilePhotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CoverPhotoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout PostsPanelLayout = new javax.swing.GroupLayout(PostsPanel);
        PostsPanel.setLayout(PostsPanelLayout);
        PostsPanelLayout.setHorizontalGroup(
            PostsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        PostsPanelLayout.setVerticalGroup(
            PostsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        PostsPanelScroll.setViewportView(PostsPanel);

        javax.swing.GroupLayout FriendsPanelLayout = new javax.swing.GroupLayout(FriendsPanel);
        FriendsPanel.setLayout(FriendsPanelLayout);
        FriendsPanelLayout.setHorizontalGroup(
            FriendsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        FriendsPanelLayout.setVerticalGroup(
            FriendsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        FriendsPanelScroll.setViewportView(FriendsPanel);

        jLayeredPane1.setLayer(CoverPhotoPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(PostsPanelScroll, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FriendsPanelScroll, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CoverPhotoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(PostsPanelScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FriendsPanelScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addComponent(CoverPhotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PostsPanelScroll)
                    .addComponent(FriendsPanelScroll)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        NewsFeedWindow newsFeed = new NewsFeedWindow();
        newsFeed.setVisible(true);
        dispose();
    }//GEN-LAST:event_ReturnButtonActionPerformed

    private void SettingsWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsWindowActionPerformed
        SettingsWindow settingsWindow = new SettingsWindow(this);
        settingsWindow.setVisible(true);
        settingsWindow.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_SettingsWindowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
User user = new User("test@example.com", "testuser", "password", "01/01/1990", "profilePhotoPath", "coverPhotoPath", "This is a bio.");

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile(user).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CoverPhotoPanel;
    private javax.swing.JPanel FriendsPanel;
    private javax.swing.JScrollPane FriendsPanelScroll;
    private javax.swing.JPanel PostsPanel;
    private javax.swing.JScrollPane PostsPanelScroll;
    private javax.swing.JPanel ProfilePhotoPanel;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JButton SettingsWindow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
